# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: thatseeyou's blog pages
#email: 
description: > # this means to ignore newlines until "baseurl:"
  Blogs for software development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thatseeyou.github.io" # the base hostname & protocol for your site
twitter_username: thatseeyou
github_username:  thatseeyou

# Build settings
markdown: kramdown

# overridable github defaults
#github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

# not overridable github defaults
# https://help.github.com/articles/configuring-jekyll/
lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
